### ISSUE TITLE
url parameter can't be extended

### ISSUE THREAD

**Issue by gregxsanders** [looker/block-gcp-billing#3]
I can't overwrite the url link in extended LookML, rather it appends another link because that's how we handle the HTML parameter in case the user wants a bunch of links. Seems minor, but it means if you create UDDs out of this content that the links to other dashboards go to the LookML dashboards or break if you've deleted those files and the best you can do is add another non-broken link to the right content in the drill menu. So, can we comment out the url parameter in the total_cost measure in gcp_billing_export_core.view.lkml ? Or is there another solution?

**Comment by jeffrey-martinez** [comment]
@gregxsanders thanks for the heads up. I've moved the url param to the config layer so it can be edited/commented out. 

Changes should be live on the marketplace within a few days! https://github.com/looker/marketplace-backend/pull/529
